In [1]:
print("HELLO CAMELS!")

HELLO CAMELS!

In [2]:
import os
print(os.listdir())

['.ipynb_checkpoints', '01013500_lump_cida_forcing_leap.txt', '01013500_streamflow_qc.txt', 'day2_load_data.ipynb']

In [7]:
import pandas as pd

In [8]:
df = pd.read_csv("01013500_streamflow_qc.txt", sep="\t", skiprows=30, names=["basin", "year", "month", "day", "streamflow", "flag"])

In [9]:
df.head()

                            basin  year  month  day  streamflow  flag
0  01013500 1980 01 31   455.00 A   NaN    NaN  NaN         NaN   NaN
1  01013500 1980 02 01   445.00 A   NaN    NaN  NaN         NaN   NaN
2  01013500 1980 02 02   440.00 A   NaN    NaN  NaN         NaN   NaN
3  01013500 1980 02 03   425.00 A   NaN    NaN  NaN         NaN   NaN
4  01013500 1980 02 04   415.00 A   NaN    NaN  NaN         NaN   NaN

In [10]:
df.describe()

       year  month  day  streamflow  flag
count   0.0    0.0  0.0         0.0   0.0
mean    NaN    NaN  NaN         NaN   NaN
std     NaN    NaN  NaN         NaN   NaN
min     NaN    NaN  NaN         NaN   NaN
25%     NaN    NaN  NaN         NaN   NaN
50%     NaN    NaN  NaN         NaN   NaN
75%     NaN    NaN  NaN         NaN   NaN
max     NaN    NaN  NaN         NaN   NaN

df.info()

#روز 2 تیر داده دبی حوضه 01013500 با پانداس بارگزاری شد